[
{ch:14,q:"How is finance best described in a business context?",choices:["The process of a business obtaining and managing the money needed to buy or do something for a particular purpose","The total profit a business earns in a single year","A legal document required to register a new business","The process of hiring new employees"],explain:"Finance is about businesses obtaining the money needed for a purpose and managing it carefully to meet the needs of society in a sustainable manner."},
{ch:14,q:"What are the two main categories of business expenditure introduced in this topic?",choices:["Capital expenditure and revenue expenditure","Fixed expenditure and variable expenditure","Direct expenditure and indirect expenditure","Internal expenditure and external expenditure"],explain:"The two main categories of expenditure are capital expenditure (spending on long-term assets) and revenue expenditure (spending on day-to-day operations)."},
{ch:14,q:"What is capital expenditure?",choices:["Spending by a business on long-term or non-current assets used for more than one year, such as buildings, machinery, and equipment","Spending on raw materials used up within the accounting period","The total revenue earned by a business in a year","Money paid out as dividends to shareholders"],explain:"Capital expenditure covers long-term, non-current assets that will be used by the business for more than one year."},
{ch:14,q:"Which of the following would be classified as capital expenditure?",choices:["A coffee shop purchasing a new espresso machine","A coffee shop purchasing coffee beans for daily use","A coffee shop paying its staff's weekly wages","A coffee shop paying its monthly electricity bill"],explain:"An espresso machine is a long-term asset that will be used for more than a year, making its purchase a capital expenditure, unlike beans, wages, and utility bills, which are revenue expenditures."},
{ch:14,q:"What is revenue expenditure?",choices:["The ongoing, short-term expenses needed to run day-to-day business operations within the accounting period, such as raw materials and wages","Spending exclusively on non-current assets like buildings and machinery","The income a business earns from selling goods or services","A one-time payment used to start a new business"],explain:"Revenue expenditure covers short-term, recurring operating expenses such as purchasing stock and paying wages and salaries, used up within about 12 months."},
{ch:14,q:"Which of the following would be classified as revenue expenditure?",choices:["Paying weekly wages to sales staff","Purchasing a new factory building","Purchasing new production machinery","Purchasing computer equipment expected to be used for several years"],explain:"Wages are an ongoing, short-term operating expense, making them revenue expenditure, unlike a factory, machinery, or long-lasting computer equipment, which are capital expenditures."},
{ch:14,q:"Revenue expenditures are also known by which alternative name?",choices:["Operating expenses","Non-current liabilities","Fixed assets","Retained earnings"],explain:"Revenue expenditures are also called operating expenses, since they consist of the short-term expenses used to run day-to-day operations."},
{ch:14,q:"Purchasing stock (inventory) is an example of which type of expenditure?",choices:["Revenue expenditure","Capital expenditure","Neither capital nor revenue expenditure","Only capital expenditure for retail businesses"],explain:"Purchasing stock is a short-term, recurring cost incurred to generate revenue within the accounting period, making it a revenue expenditure."},
{ch:14,q:"What does the triple bottom line (TBL) framework evaluate a business on?",choices:["People (social), planet (environmental), and profit (financial)","Price, promotion, and place","Assets, liabilities, and equity","Fixed costs, variable costs, and total costs"],explain:"The triple bottom line evaluates organizational performance across three pillars: people (social), planet (environmental), and profit (financial)."},
{ch:14,q:"According to the triple bottom line framework, how should profit be achieved?",choices:["Without compromising the social (people) or environmental (planet) pillars","By focusing exclusively on financial performance regardless of social or environmental impact","By eliminating all forms of environmental reporting","By reducing all employee wages to the legal minimum"],explain:"The TBL framework states that profit should be achievable without compromising the social and environmental pillars, and that negative impacts should be included when reporting profitability."},
{ch:14,q:"What does the 'people' pillar of the triple bottom line refer to?",choices:["An organization practicing fair and equitable treatment of its employees and other internal and external stakeholders","The total number of customers a business has","The number of shareholders who own the company","The size of a company's board of directors"],explain:"The 'people' (social) pillar of the TBL concerns fair and equitable treatment of employees and other stakeholders."},
{ch:14,q:"What does the 'planet' pillar of the triple bottom line refer to?",choices:["A firm's commitment to minimize the environmental impact of its business operations","The physical size of a company's premises","The number of countries a business operates in","The total value of a company's non-current assets"],explain:"The 'planet' (environmental) pillar concerns a firm's commitment to minimizing the environmental impact of its operations."},
{ch:14,q:"Why is understanding capital versus revenue expenditure useful when later studying sources of finance (3.2)?",choices:["Because businesses use different internal and external sources of finance depending on whether they are funding capital or revenue expenditures","Because capital expenditure never needs to be financed at all","Because revenue expenditure is always funded by share capital only","Because sources of finance are unrelated to the type of expenditure being funded"],explain:"Different sources of finance suit different purposes: some, like long-term loans, suit capital expenditure, while others, like overdrafts and trade credit, suit short-term revenue expenditure."},
{ch:14,q:"How does capital expenditure typically appear in a business's final accounts (3.4)?",choices:["The value of non-current assets purchased through capital expenditure, and how they are funded, is captured on the balance sheet","Capital expenditure never appears anywhere in the final accounts","Capital expenditure is always shown only in the cash flow statement","Capital expenditure is recorded exclusively as a reduction in revenue"],explain:"Non-current assets purchased through capital expenditure, and their funding, are recorded on the statement of financial position (balance sheet)."},
{ch:14,q:"Why might a profitable business still face insolvency, as raised as a research question in this topic?",choices:["Because profitability and having enough cash available to pay debts as they fall due are not the same thing","Because profitable businesses are legally protected from ever becoming insolvent","Because insolvency only affects businesses that make a loss","Because revenue expenditure guarantees a business will never run out of cash"],explain:"A business can be profitable on paper (as shown in its income statement) but still become insolvent if it does not have enough cash available when debts are due, which is why cash flow and finance management matter alongside profit."}
]
