[
{ch:29,q:"What is the overarching goal of operations management?",choices:["To ensure that business operations use as few resources as possible while meeting customer requirements","To maximize the number of employees hired by a business","To eliminate all forms of production planning","To ensure a business never changes its production methods"],explain:"Operations management aims to use as few resources as possible while still meeting what customers require from the goods or services produced."},
{ch:29,q:"How is operations management best described?",choices:["The functional area covering the design and control of production processes and business operations involved in producing goods and services","The department responsible only for hiring and training new staff","The process of setting a business's marketing budget","The department that manages a company's shareholders"],explain:"Operations management encompasses designing and controlling the production processes and operations behind a business's goods and services."},
{ch:29,q:"Does the importance of operations management depend on the size of a business?",choices:["No, operations management plays an integral part in success regardless of business size, from large assembly lines to an independent donut store","Yes, only very large businesses need to consider operations management","Yes, only online businesses need to consider operations management","No, operations management only matters for manufacturing businesses"],explain:"Operations management matters for businesses of every size, from large-scale motor assembly lines to a small, independent store."},
{ch:29,q:"What does demand and supply analysis, as a key element of operations management, involve?",choices:["Understanding product demand, supply requirements, and business forecasting","Setting the final selling price of a product","Recruiting and training new employees","Preparing a company's annual financial statements"],explain:"Demand and supply analysis focuses on understanding product demand, supply requirements, and forecasting, which is critical in manufacturing operations."},
{ch:29,q:"What does inventory management, as an element of operations management, include?",choices:["Management of raw materials, quality of goods and services, and finished products","Managing a company's relationship with its shareholders","Deciding on a business's long-term marketing strategy","Calculating a business's corporation tax liability"],explain:"Inventory management covers raw materials, the quality of goods and services, and finished products held by a business."},
{ch:29,q:"What does supply chain management involve?",choices:["Everything from sourcing raw materials to product storage to distribution","Only the marketing of a finished product","Only the recruitment of factory workers","Only the pricing strategy of a business"],explain:"Supply chain management spans the whole journey from sourcing raw materials, through storage, to final distribution of the product."},
{ch:29,q:"What does capacity management, as an element of operations management, evaluate?",choices:["Production capacity needed based on demand, productivity, and input inventory","The number of shareholders a business should have","The interest rate a business should pay on a loan","The advertising budget for a new product launch"],explain:"Capacity management evaluates how much production capacity is needed, based on demand, productivity, and the inventory of inputs available."},
{ch:29,q:"What does process and layout strategy, as an element of operations management, cover?",choices:["Factory and workplace layouts, operational processes, and production methods","The design of a company's logo and branding","The structure of a company's board of directors","The method used to calculate depreciation on assets"],explain:"Process and layout strategy concerns how a factory or workplace is laid out and which operational processes and production methods are used, all critical for business output."},
{ch:29,q:"What does geography strategy, as an element of operations management, involve?",choices:["Evaluating locations for factories, warehouses, distribution centers, and retail outlets","Deciding which countries a business should export its financial statements to","Setting exchange rates for international transactions","Choosing which currency to record accounts in"],explain:"Geography strategy involves evaluating the best locations for a business's factories, warehouses, distribution centers, and retail outlets."},
{ch:29,q:"Which other functional areas does operations management rely on to be effective, according to the text?",choices:["Finance and marketing","Human resources and legal only","Marketing and legal only","No other functional areas; operations works independently"],explain:"Finance secures and allocates resources and funds for operations, while marketing assesses consumer wants and provides feedback that informs future production planning, so operations, finance, and marketing are closely linked."},
{ch:29,q:"What role does the finance department play in supporting operations management?",choices:["Securing resources at favorable prices, allocating them throughout the organization, budgeting, analyzing investment proposals, and providing funds for operations","Manufacturing all of the business's physical products","Setting the exact production schedule for the factory floor","Designing the packaging for new products"],explain:"Finance supports operations by securing and allocating resources, budgeting, analyzing investment proposals, and funding operational activities."},
{ch:29,q:"How does the marketing department support operations management?",choices:["By assessing consumer wants and needs and providing feedback on product success that informs future production planning","By directly setting the production capacity of the factory","By managing the company's supply chain independently of operations","By preparing the company's financial statements"],explain:"Marketing assesses what consumers want and provides feedback on how well products are performing, which informs the operations team's future production planning."},
{ch:29,q:"What does the triple bottom line (TBL) suggest firms should focus on, beyond generating profit?",choices:["Measuring their social and environmental impact in addition to their financial performance","Focusing solely on maximizing short-term profit","Reducing all spending on operations to zero","Eliminating supply chains entirely"],explain:"The TBL suggests firms should commit to measuring social and environmental impact, in addition to the standard financial 'bottom line' of profit."},
{ch:29,q:"How does operations management contribute to achieving the triple bottom line?",choices:["By looking at the sustainability of supply chains and the impact of operations on local communities, and improving supply chains for favorable outcomes","By ignoring the environmental impact of production entirely","By focusing exclusively on maximizing output regardless of community impact","By removing all links between operations and sustainability goals"],explain:"Operations management supports the TBL by considering supply chain sustainability and the impact of operations on local communities, and by working to improve outcomes for all involved."},
{ch:29,q:"What is a circular supply model, as mentioned in relation to operations management?",choices:["A model that uses renewable or recovered materials, reducing demand for the extraction of new resources","A model where products are only ever sold once and never reused","A model that eliminates the need for any supply chain","A model exclusively used for financial reporting"],explain:"Circular supply models rely on renewable or recovered materials, reducing the need to extract new resources and benefiting both business and society through reduced waste and lower energy use."}
]
