[
{ch:74,q:"What is the derivative of f(x) = e^x?",choices:["e^x", "x e^(x-1)", "e^x times x", "1"],explain:"The exponential function e^x is its own derivative: d/dx(e^x) = e^x."},
{ch:74,q:"Why is e^x called 'its own derivative'?",choices:["Because differentiating e^x gives back e^x", "Because its integral equals its derivative", "Because e^x is always equal to 1", "Because e^x has no derivative"],explain:"d/dx(e^x) = e^x, so the function and its derivative are identical."},
{ch:74,q:"What is d/dx(e^x) at x = 0?",choices:["1", "0", "e", "e^2"],explain:"d/dx(e^x) = e^x, and e^0 = 1."},
{ch:74,q:"What is d/dx(e^x) at x = 1?",choices:["e", "1", "0", "e^2"],explain:"d/dx(e^x) = e^x, and at x = 1 this equals e (approximately 2.72)."},
{ch:74,q:"For a composite function e^(g(x)), what is d/dx[e^(g(x))]?",choices:["e^(g(x)) times g'(x)", "e^(g(x))", "g(x) times e^(g(x)-1)", "e^(g'(x))"],explain:"The chain rule gives d/dx[e^(g(x))] = e^(g(x)) times g'(x)."},
{ch:74,q:"Differentiate y = e^(2x).",choices:["2e^(2x)", "e^(2x)", "2xe^(2x-1)", "e^2"],explain:"With g(x) = 2x, g'(x) = 2, so dy/dx = e^(2x) times 2 = 2e^(2x)."},
{ch:74,q:"Differentiate y = e^(5x).",choices:["5e^(5x)", "e^(5x)", "e^5", "5xe^(5x)"],explain:"With g(x) = 5x, g'(x) = 5, so dy/dx = 5e^(5x)."},
{ch:74,q:"Differentiate y = e^(x^2).",choices:["2x e^(x^2)", "e^(x^2)", "x^2 e^(x^2-1)", "2e^(x^2)"],explain:"With g(x) = x^2, g'(x) = 2x, so dy/dx = 2x e^(x^2)."},
{ch:74,q:"Differentiate y = e^(3x^2 - x).",choices:["(6x - 1)e^(3x^2 - x)", "(6x)e^(3x^2 - x)", "e^(3x^2 - x)", "(3x^2 - x)e^(3x^2 - x - 1)"],explain:"With g(x) = 3x^2 - x, g'(x) = 6x - 1, so dy/dx = (6x - 1)e^(3x^2 - x)."},
{ch:74,q:"Differentiate y = e^(-x).",choices:["-e^(-x)", "e^(-x)", "-x e^(-x-1)", "x e^(-x)"],explain:"With g(x) = -x, g'(x) = -1, so dy/dx = -e^(-x)."},
{ch:74,q:"Differentiate y = e^(4 - x^3).",choices:["-3x^2 e^(4 - x^3)", "3x^2 e^(4 - x^3)", "e^(4 - x^3)", "-x^3 e^(4 - x^3)"],explain:"With g(x) = 4 - x^3, g'(x) = -3x^2, so dy/dx = -3x^2 e^(4 - x^3)."},
{ch:74,q:"What is the derivative of ln(x) for x > 0?",choices:["1/x", "x", "ln(x)", "1/ln(x)"],explain:"d/dx(ln x) = 1/x, for x > 0."},
{ch:74,q:"What is d/dx(ln x) at x = 2?",choices:["0.5", "2", "ln(2)", "1"],explain:"d/dx(ln x) = 1/x, so at x = 2 this is 1/2 = 0.5."},
{ch:74,q:"What is d/dx(ln x) at x = 5?",choices:["0.2", "5", "ln(5)", "1/ln(5)"],explain:"d/dx(ln x) = 1/x, so at x = 5 this is 1/5 = 0.2."},
{ch:74,q:"Why is the derivative of ln(x) only valid for x > 0?",choices:["Because ln(x) is only defined for x > 0", "Because derivatives never exist for negative numbers", "Because 1/x is undefined for all x", "Because ln(x) equals zero for negative x"],explain:"The natural logarithm ln(x) is only defined for positive x, so its derivative is also only considered there."},
{ch:74,q:"For a composite function ln(g(x)), what is d/dx[ln(g(x))]?",choices:["g'(x)/g(x)", "1/g(x)", "g'(x) times ln(g(x))", "g(x)/g'(x)"],explain:"The chain rule gives d/dx[ln(g(x))] = g'(x)/g(x)."},
{ch:74,q:"Differentiate y = ln(3x).",choices:["1/x", "3/x", "1/(3x)", "3x"],explain:"With g(x) = 3x, g'(x) = 3, so dy/dx = 3/(3x) = 1/x."},
{ch:74,q:"Differentiate y = ln(x^2 + 1).",choices:["2x/(x^2 + 1)", "1/(x^2 + 1)", "2x", "x^2/(2x)"],explain:"With g(x) = x^2 + 1, g'(x) = 2x, so dy/dx = 2x/(x^2 + 1)."},
{ch:74,q:"Differentiate y = ln(x^2 + 4x).",choices:["(2x + 4)/(x^2 + 4x)", "(2x)/(x^2 + 4x)", "1/(x^2 + 4x)", "(2x + 4)"],explain:"With g(x) = x^2 + 4x, g'(x) = 2x + 4, so dy/dx = (2x + 4)/(x^2 + 4x)."},
{ch:74,q:"Differentiate y = ln(5 - 2x).",choices:["-2/(5 - 2x)", "2/(5 - 2x)", "-2", "1/(5 - 2x)"],explain:"With g(x) = 5 - 2x, g'(x) = -2, so dy/dx = -2/(5 - 2x)."},
{ch:74,q:"Differentiate y = ln(x^3).",choices:["3/x", "1/x^3", "3x^2/x^3", "x^2/3"],explain:"With g(x) = x^3, g'(x) = 3x^2, so dy/dx = 3x^2/x^3 = 3/x. (Note this also follows from ln(x^3) = 3ln(x).)"},
{ch:74,q:"Differentiate y = ln(cos x), using the chain rule.",choices:["-tan(x)", "tan(x)", "-sin(x)/cos(x) times (-1)", "1/cos(x)"],explain:"With g(x) = cos x, g'(x) = -sin x, so dy/dx = -sin(x)/cos(x) = -tan(x)."},
{ch:74,q:"What is the general formula for the derivative of a^x, where a > 0 and a is not 1?",choices:["a^x ln(a)", "x a^(x-1)", "a^x", "a^x / ln(a)"],explain:"Writing a^x = e^(x ln a) and using the chain rule gives d/dx(a^x) = a^x ln(a)."},
{ch:74,q:"How is a^x rewritten in terms of e before differentiating?",choices:["a^x = e^(x ln a)", "a^x = e^x times a", "a^x = ln(a) times e^x", "a^x = e^(a ln x)"],explain:"Using the identity a = e^(ln a), we get a^x = (e^(ln a))^x = e^(x ln a)."},
{ch:74,q:"Differentiate y = 2^x.",choices:["2^x ln(2)", "2^x", "x 2^(x-1)", "2^x / ln(2)"],explain:"Using d/dx(a^x) = a^x ln(a) with a = 2, dy/dx = 2^x ln(2)."},
{ch:74,q:"Differentiate y = 3^x.",choices:["3^x ln(3)", "3^x", "x 3^(x-1)", "ln(3)"],explain:"Using d/dx(a^x) = a^x ln(a) with a = 3, dy/dx = 3^x ln(3)."},
{ch:74,q:"Differentiate y = 10^x.",choices:["10^x ln(10)", "10^x", "10 ln(x)", "x 10^(x-1)"],explain:"Using d/dx(a^x) = a^x ln(a) with a = 10, dy/dx = 10^x ln(10)."},
{ch:74,q:"Find dy/dx for y = 2^x at x = 3 (to 3 significant figures).",choices:["5.55", "8.00", "2.08", "5.77"],explain:"dy/dx = 2^x ln(2). At x = 3: 2^3 ln(2) = 8 ln(2) is approximately 5.55."},
{ch:74,q:"What happens to the general formula d/dx(a^x) = a^x ln(a) when a = e?",choices:["It reduces to e^x, since ln(e) = 1", "It becomes undefined", "It reduces to e^x ln(x)", "It becomes zero"],explain:"Since ln(e) = 1, the formula a^x ln(a) becomes e^x times 1 = e^x, matching the standard result."},
{ch:74,q:"Differentiate y = 5^(2x).",choices:["2(5^(2x)) ln(5)", "5^(2x) ln(5)", "2(5^(2x))", "5^(2x)"],explain:"With g(x) = 2x inside, using the chain rule: dy/dx = 5^(2x) ln(5) times 2 = 2(5^(2x)) ln(5)."},
{ch:74,q:"Differentiate y = x^2 e^x using the product rule.",choices:["x(2 + x)e^x", "2x e^x", "x^2 e^x", "2x + e^x"],explain:"With u = x^2, v = e^x: dy/dx = 2x e^x + x^2 e^x = x(2 + x)e^x."},
{ch:74,q:"Differentiate y = x e^x using the product rule.",choices:["(1 + x)e^x", "e^x", "x e^x", "e^x + x"],explain:"With u = x, v = e^x: dy/dx = 1 times e^x + x times e^x = (1 + x)e^x."},
{ch:74,q:"Differentiate y = (x + 1)e^x using the product rule.",choices:["(x + 2)e^x", "e^x", "(x + 1)e^x", "x e^x"],explain:"With u = x + 1, v = e^x: dy/dx = 1 times e^x + (x+1)e^x = (x + 2)e^x."},
{ch:74,q:"Differentiate y = ln(x)/x using the quotient rule.",choices:["(1 - ln(x))/x^2", "(1 + ln(x))/x^2", "1/x^2", "ln(x)/x^2"],explain:"With u = ln(x), v = x, u' = 1/x, v' = 1: dy/dx = ((1/x) times x - ln(x) times 1)/x^2 = (1 - ln(x))/x^2."},
{ch:74,q:"Differentiate y = x ln(x) using the product rule.",choices:["ln(x) + 1", "ln(x)", "1/x", "x/x"],explain:"With u = x, v = ln(x), u' = 1, v' = 1/x: dy/dx = ln(x) + x(1/x) = ln(x) + 1."},
{ch:74,q:"Differentiate y = e^x / x using the quotient rule.",choices:["e^x(x - 1)/x^2", "e^x/x^2", "e^x(x + 1)/x^2", "e^x"],explain:"With u = e^x, v = x, u' = e^x, v' = 1: dy/dx = (e^x times x - e^x times 1)/x^2 = e^x(x - 1)/x^2."},
{ch:74,q:"Differentiate y = e^x ln(x) using the product rule.",choices:["e^x ln(x) + e^x/x", "e^x/x", "e^x ln(x)", "e^x + 1/x"],explain:"With u = e^x, v = ln(x), u' = e^x, v' = 1/x: dy/dx = e^x ln(x) + e^x(1/x)."},
{ch:74,q:"Differentiate y = x^3 ln(x) using the product rule.",choices:["3x^2 ln(x) + x^2", "3x^2 ln(x)", "x^2", "x^2 ln(x) + x^2"],explain:"With u = x^3, v = ln(x), u' = 3x^2, v' = 1/x: dy/dx = 3x^2 ln(x) + x^3(1/x) = 3x^2 ln(x) + x^2."},
{ch:74,q:"What is the gradient of y = e^x at the point where x = 2, to 3 significant figures?",choices:["7.39", "2.72", "1.00", "4.00"],explain:"dy/dx = e^x, so at x = 2 the gradient is e^2, approximately 7.39."},
{ch:74,q:"What is the equation used to derive the formula for d/dx(ln x)?",choices:["e^y = x, differentiated implicitly", "y = x e^x", "ln(e) = 1", "x = y^2"],explain:"Writing y = ln(x) as e^y = x and differentiating implicitly with respect to x gives e^y (dy/dx) = 1, so dy/dx = 1/x."},
{ch:74,q:"If e^y = x and we differentiate both sides with respect to x, what do we get?",choices:["e^y (dy/dx) = 1", "e^y = 1", "y e^(y-1) (dy/dx) = 1", "dy/dx = x"],explain:"Differentiating e^y = x implicitly with respect to x gives e^y (dy/dx) = 1, using the chain rule on the left side."},
{ch:74,q:"Differentiate y = ln(2x + 3).",choices:["2/(2x + 3)", "1/(2x + 3)", "2", "ln(2)/(2x+3)"],explain:"With g(x) = 2x + 3, g'(x) = 2, so dy/dx = 2/(2x + 3)."},
{ch:74,q:"Differentiate y = e^(x/2).",choices:["0.5 e^(x/2)", "e^(x/2)", "2 e^(x/2)", "e^(0.5)"],explain:"With g(x) = x/2, g'(x) = 0.5, so dy/dx = 0.5 e^(x/2)."},
{ch:74,q:"Differentiate y = ln(x) + e^x.",choices:["1/x + e^x", "1/x", "e^x", "x + e^x"],explain:"Differentiating term by term: d/dx(ln x) = 1/x and d/dx(e^x) = e^x, so dy/dx = 1/x + e^x."},
{ch:74,q:"Differentiate y = 3e^x - 2ln(x).",choices:["3e^x - 2/x", "3e^x - 2", "e^x - 2/x", "3e^x - 2ln(x)"],explain:"Differentiating term by term with constant multiples: d/dx(3e^x) = 3e^x and d/dx(-2ln x) = -2/x, so dy/dx = 3e^x - 2/x."},
{ch:74,q:"What is d/dx(e^(g(x))) when g(x) = 7 (a constant)?",choices:["0", "e^7", "7e^7", "e^(g(x))"],explain:"If g(x) = 7 is constant, g'(x) = 0, so d/dx(e^7) = e^7 times 0 = 0, since e^7 is itself a constant."},
{ch:74,q:"A curve has equation y = ln(x). What is the gradient of the tangent line at x = 1?",choices:["1", "0", "ln(1)", "e"],explain:"dy/dx = 1/x, so at x = 1 the gradient is 1/1 = 1."},
{ch:74,q:"A curve has equation y = e^x. At which value of x does the gradient equal 1?",choices:["x = 0", "x = 1", "x = e", "x = ln(2)"],explain:"dy/dx = e^x = 1 when x = 0, since e^0 = 1."},
{ch:74,q:"A curve has equation y = ln(x). At which value of x does the gradient equal 1?",choices:["x = 1", "x = 0", "x = e", "x = ln(1)"],explain:"dy/dx = 1/x = 1 when x = 1."},
{ch:74,q:"Differentiate y = ln(x^2) using the chain rule, and simplify.",choices:["2/x", "1/x^2", "2x/x^2", "1/x"],explain:"With g(x) = x^2, g'(x) = 2x, so dy/dx = 2x/x^2 = 2/x."},
{ch:74,q:"Differentiate y = e^(2x) / e^x and simplify first using exponent rules.",choices:["e^x", "e^(2x)", "2e^x", "e^(x)/x"],explain:"Since e^(2x)/e^x = e^x (by exponent rules), dy/dx = d/dx(e^x) = e^x."},
{ch:74,q:"Which of the following is the correct chain rule derivative of e^(sin x)?",choices:["cos(x) e^(sin x)", "e^(cos x)", "sin(x) e^(sin x)", "e^(sin x)"],explain:"With g(x) = sin x, g'(x) = cos x, so d/dx[e^(sin x)] = cos(x) e^(sin x)."},
{ch:74,q:"Which of the following is the correct chain rule derivative of ln(sin x)?",choices:["cos(x)/sin(x)", "1/sin(x)", "sin(x)/cos(x)", "cos(x)"],explain:"With g(x) = sin x, g'(x) = cos x, so d/dx[ln(sin x)] = cos(x)/sin(x)."},
{ch:74,q:"If f(x) = e^(kx) for a constant k, what is f'(x)?",choices:["k e^(kx)", "e^(kx)", "k", "e^k"],explain:"With g(x) = kx, g'(x) = k, so f'(x) = k e^(kx) by the chain rule."},
{ch:74,q:"If f(x) = ln(kx) for a positive constant k, what is f'(x)?",choices:["1/x", "k/x", "1/(kx)", "k/(kx)"],explain:"With g(x) = kx, g'(x) = k, so f'(x) = k/(kx) = 1/x. (This also follows since ln(kx) = ln k + ln x.)"},
]
