[
{ch:19,q:"What is the exact value of sin 0&deg;?",choices:["0","1","undefined","-1"],explain:"sin 0&deg; = 0 since the terminal point of a 0&deg; angle on the unit circle is (1, 0)."},
{ch:19,q:"What is the exact value of cos 0&deg;?",choices:["1","0","-1","undefined"],explain:"cos 0&deg; = 1 since the terminal point of a 0&deg; angle on the unit circle is (1, 0)."},
{ch:19,q:"What is the exact value of tan 0&deg;?",choices:["0","1","undefined","-1"],explain:"tan 0&deg; = sin 0&deg; / cos 0&deg; = 0 / 1 = 0."},
{ch:19,q:"What is the exact value of sin 30&deg;?",choices:["1/2","&radic;3 / 2","&radic;2 / 2","1"],explain:"sin 30&deg; = 1/2 is a standard exact value."},
{ch:19,q:"What is the exact value of cos 30&deg;?",choices:["&radic;3 / 2","1/2","&radic;2 / 2","1"],explain:"cos 30&deg; = &radic;3 / 2 is a standard exact value."},
{ch:19,q:"What is the exact value of tan 30&deg;?",choices:["&radic;3 / 3","&radic;3","1","1/2"],explain:"tan 30&deg; = sin 30&deg; / cos 30&deg; = (1/2) / (&radic;3/2) = 1 / &radic;3 = &radic;3 / 3."},
{ch:19,q:"What is the exact value of sin 45&deg;?",choices:["&radic;2 / 2","1/2","&radic;3 / 2","1"],explain:"sin 45&deg; = &radic;2 / 2 is a standard exact value."},
{ch:19,q:"What is the exact value of cos 45&deg;?",choices:["&radic;2 / 2","&radic;3 / 2","1/2","0"],explain:"cos 45&deg; = &radic;2 / 2 is a standard exact value."},
{ch:19,q:"What is the exact value of tan 45&deg;?",choices:["1","&radic;2","&radic;2 / 2","0"],explain:"tan 45&deg; = sin 45&deg; / cos 45&deg; = 1, since sin 45&deg; = cos 45&deg;."},
{ch:19,q:"What is the exact value of sin 60&deg;?",choices:["&radic;3 / 2","1/2","&radic;2 / 2","1"],explain:"sin 60&deg; = &radic;3 / 2 is a standard exact value."},
{ch:19,q:"What is the exact value of cos 60&deg;?",choices:["1/2","&radic;3 / 2","&radic;2 / 2","0"],explain:"cos 60&deg; = 1/2 is a standard exact value."},
{ch:19,q:"What is the exact value of tan 60&deg;?",choices:["&radic;3","&radic;3 / 3","1","1/2"],explain:"tan 60&deg; = sin 60&deg; / cos 60&deg; = (&radic;3/2) / (1/2) = &radic;3."},
{ch:19,q:"What is the exact value of sin 90&deg;?",choices:["1","0","-1","undefined"],explain:"sin 90&deg; = 1 since the terminal point of a 90&deg; angle is (0, 1)."},
{ch:19,q:"What is the exact value of cos 90&deg;?",choices:["0","1","-1","undefined"],explain:"cos 90&deg; = 0 since the terminal point of a 90&deg; angle is (0, 1)."},
{ch:19,q:"What is the exact value of tan 90&deg;?",choices:["undefined","0","1","-1"],explain:"tan 90&deg; is undefined because cos 90&deg; = 0."},
{ch:19,q:"What is the exact value of sin(&pi;/6)?",choices:["1/2","&radic;3 / 2","&radic;2 / 2","1"],explain:"&pi;/6 radians is 30&deg;, so sin(&pi;/6) = 1/2."},
{ch:19,q:"What is the exact value of cos(&pi;/4)?",choices:["&radic;2 / 2","1/2","&radic;3 / 2","1"],explain:"&pi;/4 radians is 45&deg;, so cos(&pi;/4) = &radic;2 / 2."},
{ch:19,q:"What is the exact value of tan(&pi;/3)?",choices:["&radic;3","1","&radic;3 / 3","1/2"],explain:"&pi;/3 radians is 60&deg;, so tan(&pi;/3) = &radic;3."},
{ch:19,q:"What is the exact value of sin(&pi;/2)?",choices:["1","0","-1","undefined"],explain:"&pi;/2 radians is 90&deg;, so sin(&pi;/2) = 1."},
{ch:19,q:"What is the exact value of cos(&pi;)?",choices:["-1","1","0","undefined"],explain:"&pi; radians is 180&deg;, so cos(&pi;) = -1."},
{ch:19,q:"What is the exact value of sin 120&deg;?",choices:["&radic;3 / 2","-&radic;3 / 2","1/2","-1/2"],explain:"120&deg; is in quadrant II with reference angle 60&deg;; sine is positive in quadrant II, so sin 120&deg; = sin 60&deg; = &radic;3 / 2."},
{ch:19,q:"What is the exact value of cos 120&deg;?",choices:["-1/2","1/2","-&radic;3 / 2","&radic;3 / 2"],explain:"120&deg; is in quadrant II with reference angle 60&deg;; cosine is negative in quadrant II, so cos 120&deg; = -cos 60&deg; = -1/2."},
{ch:19,q:"What is the exact value of tan 120&deg;?",choices:["-&radic;3","&radic;3","-&radic;3 / 3","&radic;3 / 3"],explain:"tan 120&deg; = sin 120&deg; / cos 120&deg; = (&radic;3/2) / (-1/2) = -&radic;3."},
{ch:19,q:"What is the exact value of sin 135&deg;?",choices:["&radic;2 / 2","-&radic;2 / 2","1/2","-1/2"],explain:"135&deg; is in quadrant II with reference angle 45&deg;; sine is positive, so sin 135&deg; = sin 45&deg; = &radic;2 / 2."},
{ch:19,q:"What is the exact value of cos 135&deg;?",choices:["-&radic;2 / 2","&radic;2 / 2","-1/2","1/2"],explain:"135&deg; is in quadrant II with reference angle 45&deg;; cosine is negative, so cos 135&deg; = -cos 45&deg; = -&radic;2 / 2."},
{ch:19,q:"What is the exact value of tan 135&deg;?",choices:["-1","1","-&radic;2","&radic;2"],explain:"tan 135&deg; = sin 135&deg; / cos 135&deg; = (&radic;2/2) / (-&radic;2/2) = -1."},
{ch:19,q:"What is the exact value of sin 150&deg;?",choices:["1/2","-1/2","&radic;3 / 2","-&radic;3 / 2"],explain:"150&deg; is in quadrant II with reference angle 30&deg;; sine is positive, so sin 150&deg; = sin 30&deg; = 1/2."},
{ch:19,q:"What is the exact value of cos 150&deg;?",choices:["-&radic;3 / 2","&radic;3 / 2","-1/2","1/2"],explain:"150&deg; is in quadrant II with reference angle 30&deg;; cosine is negative, so cos 150&deg; = -cos 30&deg; = -&radic;3 / 2."},
{ch:19,q:"What is the exact value of tan 150&deg;?",choices:["-&radic;3 / 3","&radic;3 / 3","-&radic;3","&radic;3"],explain:"tan 150&deg; = sin 150&deg; / cos 150&deg; = (1/2) / (-&radic;3/2) = -&radic;3 / 3."},
{ch:19,q:"What is the exact value of sin 180&deg;?",choices:["0","1","-1","undefined"],explain:"180&deg; has terminal point (-1, 0), so sin 180&deg; = 0."},
{ch:19,q:"What is the exact value of cos 180&deg;?",choices:["-1","1","0","undefined"],explain:"180&deg; has terminal point (-1, 0), so cos 180&deg; = -1."},
{ch:19,q:"What is the exact value of tan 180&deg;?",choices:["0","undefined","1","-1"],explain:"tan 180&deg; = sin 180&deg; / cos 180&deg; = 0 / (-1) = 0."},
{ch:19,q:"What is the exact value of sin 210&deg;?",choices:["-1/2","1/2","-&radic;3 / 2","&radic;3 / 2"],explain:"210&deg; is in quadrant III with reference angle 30&deg;; sine is negative in quadrant III, so sin 210&deg; = -sin 30&deg; = -1/2."},
{ch:19,q:"What is the exact value of cos 210&deg;?",choices:["-&radic;3 / 2","&radic;3 / 2","-1/2","1/2"],explain:"210&deg; is in quadrant III with reference angle 30&deg;; cosine is negative in quadrant III, so cos 210&deg; = -cos 30&deg; = -&radic;3 / 2."},
{ch:19,q:"What is the exact value of tan 210&deg;?",choices:["&radic;3 / 3","-&radic;3 / 3","&radic;3","-&radic;3"],explain:"tan 210&deg; = sin 210&deg; / cos 210&deg; = (-1/2) / (-&radic;3/2) = &radic;3 / 3, positive since tangent is positive in quadrant III."},
{ch:19,q:"What is the exact value of sin 225&deg;?",choices:["-&radic;2 / 2","&radic;2 / 2","-1/2","1/2"],explain:"225&deg; is in quadrant III with reference angle 45&deg;; sine is negative, so sin 225&deg; = -sin 45&deg; = -&radic;2 / 2."},
{ch:19,q:"What is the exact value of cos 225&deg;?",choices:["-&radic;2 / 2","&radic;2 / 2","-1/2","1/2"],explain:"225&deg; is in quadrant III with reference angle 45&deg;; cosine is negative, so cos 225&deg; = -cos 45&deg; = -&radic;2 / 2."},
{ch:19,q:"What is the exact value of tan 225&deg;?",choices:["1","-1","&radic;2","-&radic;2"],explain:"tan 225&deg; = sin 225&deg; / cos 225&deg; = (-&radic;2/2) / (-&radic;2/2) = 1."},
{ch:19,q:"What is the exact value of sin 240&deg;?",choices:["-&radic;3 / 2","&radic;3 / 2","-1/2","1/2"],explain:"240&deg; is in quadrant III with reference angle 60&deg;; sine is negative, so sin 240&deg; = -sin 60&deg; = -&radic;3 / 2."},
{ch:19,q:"What is the exact value of cos 240&deg;?",choices:["-1/2","1/2","-&radic;3 / 2","&radic;3 / 2"],explain:"240&deg; is in quadrant III with reference angle 60&deg;; cosine is negative, so cos 240&deg; = -cos 60&deg; = -1/2."},
{ch:19,q:"What is the exact value of tan 240&deg;?",choices:["&radic;3","-&radic;3","&radic;3 / 3","-&radic;3 / 3"],explain:"tan 240&deg; = sin 240&deg; / cos 240&deg; = (-&radic;3/2) / (-1/2) = &radic;3."},
{ch:19,q:"What is the exact value of sin 270&deg;?",choices:["-1","1","0","undefined"],explain:"270&deg; has terminal point (0, -1), so sin 270&deg; = -1."},
{ch:19,q:"What is the exact value of cos 270&deg;?",choices:["0","1","-1","undefined"],explain:"270&deg; has terminal point (0, -1), so cos 270&deg; = 0."},
{ch:19,q:"What is the exact value of tan 270&deg;?",choices:["undefined","0","1","-1"],explain:"tan 270&deg; is undefined because cos 270&deg; = 0."},
{ch:19,q:"What is the exact value of sin 300&deg;?",choices:["-&radic;3 / 2","&radic;3 / 2","-1/2","1/2"],explain:"300&deg; is in quadrant IV with reference angle 60&deg;; sine is negative in quadrant IV, so sin 300&deg; = -sin 60&deg; = -&radic;3 / 2."},
{ch:19,q:"What is the exact value of cos 300&deg;?",choices:["1/2","-1/2","&radic;3 / 2","-&radic;3 / 2"],explain:"300&deg; is in quadrant IV with reference angle 60&deg;; cosine is positive in quadrant IV, so cos 300&deg; = cos 60&deg; = 1/2."},
{ch:19,q:"What is the exact value of tan 300&deg;?",choices:["-&radic;3","&radic;3","-&radic;3 / 3","&radic;3 / 3"],explain:"tan 300&deg; = sin 300&deg; / cos 300&deg; = (-&radic;3/2) / (1/2) = -&radic;3."},
{ch:19,q:"What is the exact value of sin 315&deg;?",choices:["-&radic;2 / 2","&radic;2 / 2","-1/2","1/2"],explain:"315&deg; is in quadrant IV with reference angle 45&deg;; sine is negative, so sin 315&deg; = -sin 45&deg; = -&radic;2 / 2."},
{ch:19,q:"What is the exact value of cos 315&deg;?",choices:["&radic;2 / 2","-&radic;2 / 2","1/2","-1/2"],explain:"315&deg; is in quadrant IV with reference angle 45&deg;; cosine is positive, so cos 315&deg; = cos 45&deg; = &radic;2 / 2."},
{ch:19,q:"What is the exact value of tan 315&deg;?",choices:["-1","1","&radic;2","-&radic;2"],explain:"tan 315&deg; = sin 315&deg; / cos 315&deg; = (-&radic;2/2) / (&radic;2/2) = -1."},
{ch:19,q:"In which quadrant does &theta; lie if sin&theta; &gt; 0 and cos&theta; &lt; 0?",choices:["II","I","III","IV"],explain:"sin&theta; &gt; 0 holds in quadrants I and II; cos&theta; &lt; 0 holds in quadrants II and III. The only quadrant common to both is II."},
{ch:19,q:"In which quadrant does &theta; lie if sin&theta; &lt; 0 and tan&theta; &gt; 0?",choices:["III","II","IV","I"],explain:"sin&theta; &lt; 0 holds in quadrants III and IV; tan&theta; &gt; 0 holds in quadrants I and III. The only quadrant common to both is III."},
{ch:19,q:"The terminal side of &theta; passes through the point (-&radic;2/2, &radic;2/2) on the unit circle. What is cos&theta;?",choices:["-&radic;2 / 2","&radic;2 / 2","-1/2","1/2"],explain:"On the unit circle, cos&theta; equals the x-coordinate of the terminal point, which is -&radic;2 / 2."},
{ch:19,q:"The terminal side of &theta; passes through the point (1/2, -&radic;3/2) on the unit circle. What is sin&theta;?",choices:["-&radic;3 / 2","&radic;3 / 2","1/2","-1/2"],explain:"On the unit circle, sin&theta; equals the y-coordinate of the terminal point, which is -&radic;3 / 2."},
{ch:19,q:"Given that sin&theta; = -&radic;3/2 and cos&theta; = 1/2, what is tan&theta;?",choices:["-&radic;3","&radic;3","-&radic;3 / 3","&radic;3 / 3"],explain:"tan&theta; = sin&theta; / cos&theta; = (-&radic;3/2) / (1/2) = -&radic;3."}
]
